import { Link } from 'react-router-dom'

const AnalysisResult = ({ result }) => {
  const { overall_score, section_scores, feedback, recommendations, analysis_id } = result

  // HTML-escape helper to prevent XSS from LLM output
  const escapeHTML = (str) => {
    if (!str) return ''
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
  }

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-emerald-500'
    if (score >= 60) return 'text-amber-500'
    return 'text-red-500'
  }

  const getScoreGradient = (score) => {
    if (score >= 80) return 'from-emerald-400 to-emerald-500'
    if (score >= 60) return 'from-amber-400 to-amber-500'
    return 'from-red-400 to-red-500'
  }

  const getScoreLabel = (score) => {
    if (score >= 80) return 'Excellent'
    if (score >= 60) return 'Good'
    return 'Needs Work'
  }

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    const sectionHTML = Object.entries(section_scores).map(([section, score]) => `
      <div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin-bottom: 8px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <span style="font-weight: 600; text-transform: capitalize;">${escapeHTML(section.replace(/_/g, ' '))}</span>
          <span style="font-size: 20px; font-weight: 700; color: ${score >= 80 ? '#16a34a' : score >= 60 ? '#ca8a04' : '#dc2626'};">${score}/100</span>
        </div>
        <div style="background: #f3f4f6; border-radius: 4px; height: 8px; margin-top: 8px;">
          <div style="background: ${score >= 80 ? '#16a34a' : score >= 60 ? '#ca8a04' : '#dc2626'}; height: 8px; border-radius: 4px; width: ${Math.min(score, 100)}%;"></div>
        </div>
      </div>
    `).join('')

    const feedbackHTML = Object.entries(feedback).map(([section, text]) => `
      <div style="border-left: 4px solid #6366f1; padding-left: 16px; margin-bottom: 16px;">
        <h4 style="font-weight: 700; text-transform: capitalize; margin-bottom: 4px;">${escapeHTML(section.replace(/_/g, ' '))}</h4>
        <p style="color: #374151; line-height: 1.6;">${escapeHTML(text)}</p>
      </div>
    `).join('')

    const recsHTML = recommendations?.map(rec => `<li style="margin-bottom: 8px;">&rarr; ${escapeHTML(rec)}</li>`).join('') || ''

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>VCRAFT AI - Pitch Analysis Report</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111827; }
          h1 { color: #4f46e5; margin-bottom: 4px; }
          .subtitle { color: #6b7280; margin-bottom: 32px; }
          .score-card { text-align: center; background: linear-gradient(135deg, #eef2ff, #e0e7ff); padding: 32px; border-radius: 12px; margin-bottom: 32px; }
          .score-number { font-size: 64px; font-weight: 800; color: ${overall_score >= 80 ? '#16a34a' : overall_score >= 60 ? '#ca8a04' : '#dc2626'}; }
          .section-title { font-size: 20px; font-weight: 700; margin: 24px 0 16px 0; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>VCRAFT AI</h1>
        <p class="subtitle">Pitch Analysis Report &bull; Generated ${new Date().toLocaleDateString()}</p>
        
        <div class="score-card">
          <div class="score-number">${overall_score}</div>
          <p style="font-size: 18px; color: #4b5563;">Overall Score - ${getScoreLabel(overall_score)}</p>
        </div>

        <div class="section-title">Section Breakdown</div>
        ${sectionHTML}

        <div class="section-title">Detailed Feedback</div>
        ${feedbackHTML}

        ${recommendations?.length ? `
          <div class="section-title">Key Recommendations</div>
          <ul style="padding-left: 0; list-style: none;">${recsHTML}</ul>
        ` : ''}

        <div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px;">
          Generated by VCRAFT AI &bull; AI-Powered Pitch Analysis
        </div>
      </body>
      </html>
    `)
    printWindow.document.close()
    setTimeout(() => printWindow.print(), 500)
  }

  return (
    <div className="min-h-screen mesh-gradient relative">
      <div className="blob blob-sm bg-primary-300" style={{ top: '5%', right: '10%' }} />
      <div className="blob blob-sm bg-emerald-200" style={{ bottom: '20%', left: '5%', animationDelay: '3s' }} />

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 relative z-10">
        {/* Overall Score */}
        <div className="card mb-8 bg-gradient-to-br from-primary-500/5 to-indigo-500/5 border-primary-500/10 animate-scale-in">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-800 mb-4">
              Analysis Complete
            </h2>
            <div className="inline-block">
              <div className={`text-7xl font-extrabold ${getScoreColor(overall_score)} mb-2`}>
                {overall_score}
              </div>
              <p className="text-lg text-gray-500 font-medium">
                Overall Score — {getScoreLabel(overall_score)}
              </p>
            </div>
          </div>
        </div>

        {/* Section Scores */}
        <div className="card mb-8 animate-fade-in-up" style={{ animationDelay: '100ms' }}>
          <h3 className="text-2xl font-extrabold text-gray-800 mb-6 flex items-center gap-2">
            <span className="w-8 h-8 bg-blue-500/10 rounded-lg flex items-center justify-center text-sm">📊</span>
            Section Breakdown
          </h3>
          
          <div className="grid md:grid-cols-2 gap-5">
            {Object.entries(section_scores).map(([section, score], idx) => (
              <div key={section} className="stat-card animate-fade-in-up" style={{ animationDelay: `${(idx + 2) * 80}ms` }}>
                <div className="flex justify-between items-center mb-3">
                  <h4 className="font-bold text-gray-700 capitalize">
                    {section.replace(/_/g, ' ')}
                  </h4>
                  <span className={`text-2xl font-extrabold ${getScoreColor(score)}`}>
                    {score}
                  </span>
                </div>
                <div className="progress-bar">
                  <div 
                    className={`fill bg-gradient-to-r ${getScoreGradient(score)}`}
                    style={{ width: `${score}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Detailed Feedback */}
        <div className="card mb-8 animate-fade-in-up" style={{ animationDelay: '200ms' }}>
          <h3 className="text-2xl font-extrabold text-gray-800 mb-6 flex items-center gap-2">
            <span className="w-8 h-8 bg-violet-500/10 rounded-lg flex items-center justify-center text-sm">💬</span>
            Detailed Feedback
          </h3>
          
          <div className="space-y-5">
            {Object.entries(feedback).map(([section, text]) => (
              <div key={section} className="border-l-4 border-primary-400/60 pl-4 py-1">
                <h4 className="font-bold text-gray-700 mb-2 capitalize">
                  {section.replace(/_/g, ' ')}
                </h4>
                <p className="text-gray-500 leading-relaxed">{text}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Recommendations */}
        {recommendations && recommendations.length > 0 && (
          <div className="card mb-8 animate-fade-in-up" style={{ animationDelay: '300ms' }}>
            <h3 className="text-2xl font-extrabold text-gray-800 mb-6 flex items-center gap-2">
              <span className="w-8 h-8 bg-amber-500/10 rounded-lg flex items-center justify-center text-sm">💡</span>
              Key Recommendations
            </h3>
            
            <ul className="space-y-3">
              {recommendations.map((rec, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="w-6 h-6 bg-primary-500/10 rounded-full flex items-center justify-center text-primary-600 font-bold text-xs flex-shrink-0 mt-0.5">{index + 1}</span>
                  <span className="text-gray-600">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Actions */}
        <div className="flex flex-wrap gap-3 animate-fade-in-up" style={{ animationDelay: '400ms' }}>
          <Link 
            to={`/chat/${analysis_id}`}
            className="btn-primary flex-1 text-center"
          >
            💬 Chat with VC Investor
          </Link>
          <Link 
            to={`/qa/${analysis_id}`}
            className="btn-secondary flex-1 text-center"
          >
            Classic Q&A
          </Link>
          <button
            onClick={handleExportPDF}
            className="btn-secondary flex-1 text-center"
          >
            📥 Export as PDF
          </button>
          <Link 
            to="/dashboard"
            className="btn-secondary flex-1 text-center"
          >
            Dashboard
          </Link>
        </div>
      </div>
    </div>
  )
}

export default AnalysisResult
